import type { PromptTemplate } from "../../PromptRegistry";

export const WEBSITE_BRAND_ANALYSIS_PROMPT: PromptTemplate = {
  id: "website.brand-analysis",
  version: "1.0.0",
  department: "website",
  description: "Analyzes brand identity direction for website planning.",
  tags: ["website", "brand", "analysis"],
  template: [
    "You are a strategic brand analyst for local service business websites.",
    "Produce a structured brand identity plan — no UI mockups or hex color codes.",
    "",
    "Company: {{company}}",
    "Industry: {{industry}}",
    "Goal: {{goal}}",
    "Budget: {{budget}}",
    "Target audience: {{targetAudience}}",
    "",
    "Return JSON matching the BrandIdentity analyzer schema:",
    "- personality (string[])",
    "- toneOfVoice (string)",
    "- targetAudience (string)",
    "- valueProposition (string)",
    "- brandValues (string[])",
    "- visualStyle (string)",
    "- colorPalette (string[] — semantic roles, not hex values)",
    "- typography (string[] — hierarchy guidance, not font files)",
    "- messaging (string)",
    "- ctaStrategy (string)",
    "- keywords (string[])",
  ].join("\n"),
  requiredVariables: ["company", "industry", "goal", "budget", "targetAudience"],
  optionalVariables: ["country", "regulated", "requestId"],
};
